name: Issue Report
description:  Report a bug or related issue with the mod 
body:
  - type: input
    id: forge-version
    attributes:
      label: Mod Loader
      placeholder: eg. forge-43.2.21
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod version
      placeholder: eg. Goety 2.18.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue description
      description: "A clear description of the issue you are having."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Link or Post Log Files
      description: "Link or post any log files that can help debugging"
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: "How is this issue repeateable? Ignore this, if it's not repeateable."
      placeholder: |
        1. First step
        2. Second step
        3. etc...
  - type: textarea
    attributes:
      label: Additional information
      description: Any other relevant information that is related to this issue.
